---
# tasks file for projet_ansible/roles/ssh_users
- name: Création du user devops
  user:
    name: devops
    shell: /bin/bash
    groups: sudo
    append: yes
    password: "{{ 'kirikou' | password_hash('sha512') }}"
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa

- name: Ajouter le user dans les sudoers
  copy:
    dest: "/etc/sudoers.d/devops"
    content: "devops ALL=(ALL) NOPASSWD: ALL"
  become: true
- name: Deploiement de la clé ssh
  authorized_key:
    user: devops
    key: "{{ lookup('file', '/tmp/cle_ansible.pub') }}"
    state: present
  become: true
