- name: Playbook de deploiment ssh
  hosts: all
  become: true
  tasks:
    - name: Génération de la clé ssh
      openssh_keypair:
        path: /tmp/cle_ansible
        state: present
        size: 4096
        type: rsa
        force: False
        comment: "Destinées aux machine all"
        # mode:
        # owner:
        # group:
        # seuser:
        # serole:
        # setype:
        # selevel: s0
        # unsafe_writes: False
        # attributes:
      delegate_to: localhost
      run_once: true

    - name: Make sure we can use htpasswd module
      apt: "pkg=python-passlib state=present"



    
    - name: Deploiement de la clé ssh
      authorized_key:
        user: devops
        key: "{{ lookup('file', '/tmp/cle_ansible.pub') }}"
        state: present # not required. choices: absent;present. Whether the given key (with the given key_options) should or should not be in the file.
        #path:  # not required. Alternate path to the authorized_keys file. When unset, this value defaults to I(~/.ssh/authorized_keys).
        #manage_dir: True # not required. Whether this module should manage the directory of the authorized key file. If set to C(yes), the module will create the directory, as well as set the owner and permissions of an existing directory. Be sure to set C(manage_dir=no) if you are using an alternate directory for authorized_keys, as set with C(path), since you could lock yourself out of SSH access. See the example below.
        #key_options:  # not required. A string of ssh key options to be prepended to the key in the authorized_keys file.
        #exclusive: False # not required. Whether to remove all other non-specified keys from the authorized_keys file. Multiple keys can be specified in a single C(key) string value by separating them by newlines. This option is not loop aware, so if you use C(with_) , it will be exclusive per iteration of the loop. If you want multiple keys in the file you need to pass them all to C(key) in a single batch as mentioned above.
        #validate_certs: True # not required. This only applies if using a https url as the source of the keys. If set to C(no), the SSL certificates will not be validated. This should only set to C(no) used on personally controlled sites using self-signed certificates as it avoids verifying the source site. Prior to 2.1 the code worked as if this was set to C(yes).
        #comment:  # not required. Change the comment on the public key. Rewriting the comment is useful in cases such as fetching it from GitHub or GitLab. If no comment is specified, the existing comment will be kept.
        #follow: False # not required. Follow path symlink instead of replacing it.